In [5]:
import glob 
import pandas

In [20]:
pandas.set_option('display.max_rows', 500)
pandas.set_option('display.max_columns', 500)

In [3]:
list_of_xlsx = glob.glob('week*.xlsx')

In [4]:
list_of_xlsx[0]

'week 13 - survey of cloud costs_Anonymous Student (Attempt ID  15926429)_attempt_2019-04-30-18-24-33_week_13_CSP_survey.xlsx'

In [7]:
list_of_df=[]
for fil in list_of_xlsx:
    df = pandas.read_excel(fil)
    print('df.shape=',df.shape)
    list_of_df.append(df)

df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (10, 4)
df.shape= (9, 4)
df.shape= (30, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)

In [10]:
list_of_df[7].shape

(10, 4)

In [11]:
list_of_df[7]

,Vendor,Microsoft,Unnamed: 2,Unnamed: 3
NaN,NaN,NaN,NaN,NaN
NaN,aspect,cost,source URL,note
NaN,storage: 1 TB for 1 year,737.28,https://azure.microsoft.com/en-us/pricing/calc...,"-Input East US, 1 TB, File Storage. Rest of in..."
NaN,storage: 100 TB for 1 year,73728,https://azure.microsoft.com/en-us/pricing/calc...,"-Input East US, 100 TB, File Storage. Rest of ..."
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",8561.53 at least per month,https://azure.microsoft.com/en-us/pricing/calc...,Using ND24
NaN,data upload: 10 TB,"Free, however in certain available areas, it c...",https://azure.microsoft.com/en-us/pricing/deta...,NaN
NaN,data download: 10 TB,"According to there website, First 5 GB are fre...",https://azure.microsoft.com/en-us/pricing/deta...,NaN
NaN,NaN,NaN,NaN,NaN
NaN,Learning Lesson?,NaN,NaN,NaN
NaN,Pricing can be quite confusing and daunting ho...,NaN,NaN,NaN

In [13]:
print(list_of_df[8].shape)
list_of_df[8]

(9, 4)

,Vendor,Google,Unnamed: 2,Unnamed: 3
NaN,All pricing using Northern Virgina Region Rates,NaN,NaN,NaN
NaN,Compute pricing using 1 year commitment price,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN
NaN,aspect,cost,source URL,note
NaN,storage: 1 TB for 1 year,282.62,https://cloud.google.com/storage/pricing,"$.023 (per GB per month) * 1,024 GB * 12 months\n"
NaN,storage: 100 TB for 1 year,28262.4,https://cloud.google.com/storage/pricing,"$.023 (per GB per month) * 102,400 GB * 12 mon..."
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",47689.4,https://cloud.google.com/compute/pricing,$15.56 (per CPU per month) * 20 CPU * 12 month...
NaN,data upload: 10 TB,free,https://cloud.google.com/storage/pricing,General Network Usage category\nIngress listed...
NaN,data download: 10 TB,1136.64,https://cloud.google.com/storage/pricing,"$0.12 (per GB 0-1 TB Tier) * 1,024 GB = $122.8..."

In [14]:
print(list_of_df[9].shape)
list_of_df[9]

(30, 4)

,Vendor,Broadberry,Unnamed: 2,Unnamed: 3
NaN,NaN,NaN,NaN,NaN
NaN,Aspect,Cost,Source URL,Notes
NaN,"Intel Xeon Gold 6148 Processor - 20 Cores, 2.4...",4150.08,Broadberry configuration site,"Intel Xeon Gold 6148 Processor - 20 Cores, 2.4..."
NaN,Storage: 8x 2.4TB Enterprise Performance 10k 1...,3928.64,Same as above,8x 128GB 2666MHz DDR4 LR ECC DIMM Module
NaN,1 TB of RAM - 8x 128GB 2666MHz DDR4 LR ECC DIM...,25287.4,Same as above,5x NVIDIA RTX 2070 Graphics Card PCI-E x16 Gen...
NaN,5 GPUs - 5x NVIDIA RTX 2070 Graphics Card PCI-...,3538.65,Same as above,1 Year On-Site Warranty
NaN,Storage: 120 TB - Synology RS2418+ RackStation...,7424.19,120TB NAS storage system,Separate Network attached storage for 120 TB o...
NaN,storage: 1 TB for 1 year,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,NaN,NaN,NaN
NaN,Compute,NaN,NaN,NaN
NaN,data upload: 10 TB,NaN,NaN,NaN
NaN,data download: 10 TB,NaN,NaN,NaN
NaN,Total,44328.9,NaN,NaN
NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN
NaN,Configuration highlights,NaN,NaN,NaN
NaN,Broadberry GPU Server ESC8000 G4,NaN,NaN,NaN
NaN,"8x PCIE x16, Redundant 2400W Power, Dual Gigab...",NaN,NaN,NaN
NaN,Chassis,ESC8000-G4 Server (upto 8x GPU) 2+1 1600Watt P...,NaN,NaN
NaN,Processor,"Intel Xeon Gold 6148 Processor - 20 Cores, 2.4...",NaN,NaN
NaN,Memory,8x 128GB 2666MHz DDR4 LR ECC DIMM Module,NaN,NaN
NaN,Hard Drive,8x 2.4TB Enterprise Performance 10k 12Gb/s SAS...,NaN,NaN
NaN,RAID Controller Card,LSI MegaRAID 9361-8i 12Gb/s SAS/SATA RAID Cont...,NaN,NaN
NaN,Nvidia Tesla and AMD FirePro GPU Compute Cards,5x NVIDIA RTX 2070 Graphics Card PCI-E x16 Gen...,NaN,NaN
NaN,Upgraded Warranty,1 Year On-Site Warranty,NaN,NaN
NaN,Total Price:,48926.7,NaN,NaN

In [15]:
list_of_df=[]
for fil in list_of_xlsx:
    df = pandas.read_excel(fil)
    print('df.shape=',df.shape)
    if df.shape[0]==7:
        list_of_df.append(df)

df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (10, 4)
df.shape= (9, 4)
df.shape= (30, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)
df.shape= (7, 4)

In [18]:
all_df = pandas.concat(list_of_df,sort=False)
print(all_df.shape)
all_df.head()

(105, 15)

,Vendor,Amazon Cloud Services,Unnamed: 2,Unnamed: 3,Self-Hosted Server,<<NAME OF COMPANY>>,Google Cloud,Google,<<MICROSOFT>>,Amazon,MICROSOFT; NVIDIA (for GPUs),Microsoft,Self-hosted,Amazon AWS,Amazon Web Services
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,aspect,cost,source URL,note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,23 $,https://aws.amazon.com/s3/pricing/,For S3 Standard storage pricing it costs 0.023...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,2250 $,https://aws.amazon.com/s3/pricing/,For S3 Standard storage pricing it costs 0.023...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",80649.68 $,https://calculator.s3.amazonaws.com/index.html,For EC2 per month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
all_df.sort_values(by=['Vendor'])

,Vendor,Amazon Cloud Services,Unnamed: 2,Unnamed: 3,Self-Hosted Server,<<NAME OF COMPANY>>,Google Cloud,Google,<<MICROSOFT>>,Amazon,MICROSOFT; NVIDIA (for GPUs),Microsoft,Self-hosted,Amazon AWS,Amazon Web Services
NaN,aspect,cost,source URL,note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,aspect,NaN,source URL,note,NaN,NaN,NaN,NaN,NaN,NaN,cost,NaN,NaN,NaN,NaN
NaN,aspect,NaN,source URL,note,NaN,NaN,NaN,NaN,cost,NaN,NaN,NaN,NaN,NaN,NaN
NaN,aspect,NaN,source URL,note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cost,NaN,NaN,NaN
NaN,aspect,NaN,source URL,note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cost,NaN,NaN
NaN,aspect,NaN,source URL,note,NaN,NaN,NaN,cost,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,aspect,NaN,source URL,note,NaN,NaN,NaN,NaN,NaN,cost,NaN,NaN,NaN,NaN,NaN
NaN,aspect,NaN,source URL,note,NaN,NaN,NaN,NaN,NaN,cost,NaN,NaN,NaN,NaN,NaN
NaN,aspect,NaN,source URL,note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cost,NaN
NaN,aspect,NaN,source URL,note,NaN,cost ( in $),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,aspect,NaN,source URL,note,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cost
NaN,aspect,NaN,source URL,note,NaN,NaN,cost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,aspect,NaN,source URL,note,NaN,NaN,NaN,NaN,NaN,cost,NaN,NaN,NaN,NaN,NaN
NaN,aspect,NaN,source URL,note,NaN,NaN,NaN,cost,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,aspect,NaN,source URL,note,cost,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,compute,NaN,https://aws.amazon.com/ec2/pricing/on-demand/,On demand pricing (per hour) x1.32xlarge (19.2...,NaN,NaN,NaN,NaN,NaN,168420,NaN,NaN,NaN,NaN,NaN
NaN,compute,NaN,https://azure.microsoft.com/en-us/pricing/deta...,Unable to find exact requirements. Price show ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34689.6,NaN,NaN,NaN
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",NaN,https://calculator.s3.amazonaws.com/index.html,Linux on x1e.8xlarge - $ 5573.61 a month,NaN,NaN,NaN,NaN,NaN,66883.3,NaN,NaN,NaN,NaN,NaN
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",NaN,https://azure.microsoft.com/en-us/pricing/calc...,Effective per month it costs $1926.47,NaN,NaN,NaN,NaN,23117.6,NaN,NaN,NaN,NaN,NaN,NaN
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",80649.68 $,https://calculator.s3.amazonaws.com/index.html,For EC2 per month,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",NaN,https://cloud.google.com/products/calculator/#...,One Year,NaN,NaN,NaN,1.21659e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",NaN,https://aws.amazon.com/marketplace/pp/B07GRMYQ...,"Amazon Linux 2 AMI (HVM), SSD Volume Type \nh1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"\t$1.872/hr *24*365\n~$16,398.72/ year\n"
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",NaN,http://www.broadberry.com/xeon-e5v3-rackmount-...,"Server specs contain: 20cores, 1TB and 48TB (o...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37653.2,NaN,NaN
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",NaN,http://www.deltaserverstore.com/dell-r910.html...,"1 TB RAM,24Core + 6 GPU = ($6000+4749)",$10749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",NaN,https://cloud.google.com/products/calculator/#...,NaN,NaN,NaN,54699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",NaN,https://awstcocalculator.com/#,used the cost calculator,NaN,NaN,NaN,NaN,NaN,17160130,NaN,NaN,NaN,NaN,NaN
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",NaN,https://ark.intel.com/content/www/us/en/ark/pr...,"Cost I mentioned is refered to 20 cores ,1.5 T...",NaN,3226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",NaN,https://calculator.s3.amazonaws.com/index.html...,Amazon EC2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29075,NaN
NaN,"compute: 20 cores, 1TB of RAM, 5 GPUs",NaN,https://cloud.google.com/compute/pricing#custo...,Calculation of vcpu/memory/gpu per hour for on...,NaN,NaN,NaN,26280,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,"compute: 20 cores, 1TB of RAM, and 5 GPUs",NaN,https://www.dell.com/en-us/work/shop/accessori...,(~$467.20/month)*(2.5 (for 20 cores))*(12mns)=...,NaN,NaN,NaN,NaN,NaN,NaN,92744.6,NaN,NaN,NaN,NaN
NaN,data download: 10 TB,NaN,https://cloud.google.com/storage/pricing#netwo...,Within the same location only,NaN,NaN,NaN,500,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data download: 10 TB,NaN,https://azure.microsoft.com/en-us/pricing/deta...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,870,NaN,NaN,NaN
NaN,data download: 10 TB,NaN,https://aws.amazon.com/snowball-edge/pricing/,NaN,NaN,NaN,NaN,NaN,NaN,3000,NaN,NaN,NaN,NaN,NaN
NaN,data download: 10 TB,NaN,https://aws.amazon.com/s3/pricing/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10TB/month for $0.09 per GB\n~$90.00
NaN,data download: 10 TB,NaN,https://azure.microsoft.com/en-us/pricing/deta...,"Pricing was given under the ""Operations and da...",NaN,NaN,NaN,NaN,NaN,NaN,"*Write Operations (per 10,000) = $0.0175",NaN,NaN,NaN,NaN
NaN,data download: 10 TB,NaN,https://calculator.s3.amazonaws.com/index.html...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11058.1,NaN
NaN,data download: 10 TB,NaN,https://aws.amazon.com/s3/pricing/,Data Returned by S3 Select (S3 standard),NaN,NaN,NaN,NaN,NaN,900,NaN,NaN,NaN,NaN,NaN
NaN,data download: 10 TB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data download: 10 TB,NaN,https://calculator.s3.amazonaws.com/index.html,S3 Standard - Data Transfer Out - 833GB a mont...,NaN,NaN,NaN,NaN,NaN,147.24,NaN,NaN,NaN,NaN,NaN
NaN,data download: 10 TB,NaN,https://azure.microsoft.com/en-us/pricing/deta...,Azure Import/Export service enables you to tra...,NaN,NaN,NaN,NaN,160,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data download: 10 TB,NaN,https://www.ibm.com/cloud/bandwidth,Would be covered in above cost,$10584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data download: 10 TB,NaN,NaN,Nodes Spanner,NaN,NaN,130980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data download: 10 TB,NaN,https://cloud.google.com/storage/pricing#archi...,Year Month - Network Usage & Transfer tool fee...,NaN,NaN,NaN,12000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data download: 10 TB,NaN,https://www.enterprisestorageforum.com/cloud-s...,(0-1) TB rate is $0.12/gb and (1-10) TB rate i...,NaN,13320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data download: 10 TB,899.91 $ per month,https://aws.amazon.com/s3/pricing/,First 1GB transfer rate is 0$ as it is free .W...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data upload: 10 TB,NaN,https://aws.amazon.com/snowball-edge/pricing/,"data tranfer in is free, if that is the same t...",NaN,NaN,NaN,NaN,NaN,free?,NaN,NaN,NaN,NaN,NaN
NaN,data upload: 10 TB,NaN,https://calculator.s3.amazonaws.com/index.html...,Looks like its free with price of base EC2 ser...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
NaN,data upload: 10 TB,NaN,https://cloud.google.com/products/calculator/#...,NaN,NaN,NaN,130980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data upload: 10 TB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data upload: 10 TB,NaN,https://www.ibm.com/cloud/bandwidth,882$/month,$10584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data upload: 10 TB,NaN,https://aws.amazon.com/s3/pricing/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No Cost; Free for Data upload
NaN,data upload: 10 TB,NaN,https://azure.microsoft.com/en-us/pricing/deta...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,free,NaN,NaN,NaN
NaN,data upload: 10 TB,NaN,https://cloud.google.com/storage/pricing#netwo...,Within the same location only,NaN,NaN,NaN,Free,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data upload: 10 TB,0 $,https://aws.amazon.com/s3/pricing/,We are not charged for Data Transfer IN To Ama...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data upload: 10 TB,NaN,https://azure.microsoft.com/en-us/pricing/deta...,"Pricing was given under the ""Operations and da...",NaN,NaN,NaN,NaN,NaN,NaN,"*Read Operations (per 10,000) = $0.0014",NaN,NaN,NaN,NaN
NaN,data upload: 10 TB,NaN,https://calculator.s3.amazonaws.com/index.html,S3 Standard - Data Transfer In - 833GB a month...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
NaN,data upload: 10 TB,NaN,https://docs.microsoft.com/en-us/azure/storage...,Azure Import/Export service is used to securel...,NaN,NaN,NaN,NaN,160,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data upload: 10 TB,NaN,https://aws.amazon.com/s3/pricing/,Data Transfer IN To Amazon S3 From Internet,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN
NaN,data upload: 10 TB,NaN,https://cloud.google.com/storage/pricing#archi...,Year Month - Network Usage & Transfer tool fee...,NaN,NaN,NaN,12000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,data upload: 10 TB,NaN,https://www.enterprisestorageforum.com/cloud-s...,free data transfer to the cloud,NaN,free,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,NaN,https://cloud.google.com/storage/pricing#price...,Coldline storage only - access once a year,NaN,NaN,NaN,84,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,NaN,https://www.ebay.com/itm/NAS-Acer-Aspire-Easy-...,Buying it off.,$89.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,NaN,https://calculator.s3.amazonaws.com/index.html,S3 Standard storage - $23.44 a month,NaN,NaN,NaN,NaN,NaN,281.28,NaN,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,23 $,https://aws.amazon.com/s3/pricing/,For S3 Standard storage pricing it costs 0.023...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,NaN,https://aws.amazon.com/s3/pricing/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,First 50 TB / Month $0.023/GB\n~ $23.00
NaN,storage: 1 TB for 1 year,NaN,https://www.enterprisestorageforum.com/cloud-s...,Calculated by rate given per mb and 5gb free ...,NaN,238.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,NaN,https://calculator.s3.amazonaws.com/index.html...,Amazon S3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,281.28,NaN
NaN,storage: 1 TB for 1 year,NaN,https://aws.amazon.com/s3/pricing/,Data Transfer IN To Amazon S3 From Internet,NaN,NaN,NaN,NaN,NaN,276,NaN,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,NaN,https://cloud.google.com/products/calculator/#...,NaN,NaN,NaN,NaN,319.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,NaN,https://azure.microsoft.com/en-us/pricing/deta...,~$233.60/month*12 = $2803.20/yr,NaN,NaN,NaN,NaN,NaN,NaN,2803.2,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,NaN,https://cloud.google.com/products/calculator/#...,NaN,NaN,NaN,319.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,NaN,https://www.amazon.com/b?ie=UTF8&node=16591160011,NaN,NaN,NaN,NaN,NaN,NaN,59.99,NaN,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,NaN,https://azure.microsoft.com/en-us/pricing/calc...,per month it takes 2.77$ for 84GB therefore by...,NaN,NaN,NaN,NaN,33.24,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 1 TB for 1 year,NaN,https://azure.microsoft.com/en-us/pricing/deta...,$35 a month x 12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,420,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,NaN,https://calculator.s3.amazonaws.com/index.html,S3 Standard storage - $2534.27 a month,NaN,NaN,NaN,NaN,NaN,30411.2,NaN,NaN,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,NaN,https://azure.microsoft.com/en-us/pricing/calc...,per month for 8333.3GB data costs $174.37 ther...,NaN,NaN,NaN,NaN,2092.44,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,2250 $,https://aws.amazon.com/s3/pricing/,For S3 Standard storage pricing it costs 0.023...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,NaN,https://azure.microsoft.com/en-us/pricing/deta...,"$2,900 a month x 12",NaN,NaN,NaN,NaN,NaN,NaN,NaN,34800,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,NaN,https://cloud.google.com/storage/pricing#price...,Coldline storage only - access once a year,NaN,NaN,NaN,8400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,NaN,https://calculator.s3.amazonaws.com/index.html...,Amazon S3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27648,NaN
NaN,storage: 100 TB for 1 year,NaN,https://aws.amazon.com/s3/pricing/,First 50 TB / Month (S3 standard storage),NaN,NaN,NaN,NaN,NaN,552,NaN,NaN,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,NaN,https://www.emergentsx.com/listings/product/10...,NaN,$32400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,NaN,https://www.newegg.com/Product/Product.aspx?It...,60TB storage,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2895,NaN,NaN
NaN,storage: 100 TB for 1 year,NaN,https://aws.amazon.com/s3/pricing/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,First 50 TB / Month $0.023/GB\nNext 450 TB / M...
NaN,storage: 100 TB for 1 year,NaN,https://cloud.google.com/products/calculator/#...,NaN,NaN,NaN,32368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,NaN,https://aws.amazon.com/s3/pricing/,$1150+$1100 first 50 gigs is 0.023 per gb. Nex...,NaN,NaN,NaN,NaN,NaN,2250,NaN,NaN,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,NaN,https://www.enterprisestorageforum.com/cloud-s...,Calculated by rate given per mb and 5gb free ...,NaN,23880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,NaN,https://cloud.google.com/products/calculator/#...,NaN,NaN,NaN,NaN,"31,948.80",NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,storage: 100 TB for 1 year,NaN,https://azure.microsoft.com/en-us/pricing/deta...,"(~$467.20/month)*12*50 = ~$23,360/yr",NaN,NaN,NaN,NaN,NaN,NaN,"~$23,360",NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
list_of_df=[]
for fil in list_of_xlsx:
    df = pandas.read_excel(fil)
    print('df.shape=',df.shape)
    if df.shape[0]==7:
        print(df)

df.shape= (7, 4)
                                    Vendor Amazon Cloud Services  \
NaN                                    NaN                   NaN
NaN                                 aspect                  cost
NaN               storage: 1 TB for 1 year                  23 $
NaN             storage: 100 TB for 1 year                2250 $
NaN  compute: 20 cores, 1TB of RAM, 5 GPUs            80649.68 $
NaN                     data upload: 10 TB                   0 $
NaN                   data download: 10 TB    899.91 $ per month

                                         Unnamed: 2  \
NaN                                             NaN
NaN                                      source URL
NaN              https://aws.amazon.com/s3/pricing/
NaN              https://aws.amazon.com/s3/pricing/
NaN  https://calculator.s3.amazonaws.com/index.html
NaN              https://aws.amazon.com/s3/pricing/
NaN              https://aws.amazon.com/s3/pricing/

                                            Unnamed: 3
NaN                                                NaN
NaN                                               note
NaN  For S3 Standard storage pricing it costs 0.023...
NaN  For S3 Standard storage pricing it costs 0.023...
NaN                                  For EC2 per month
NaN  We are not charged for Data Transfer IN To Ama...
NaN  First 1GB transfer rate is 0$ as it is free .W...
df.shape= (7, 4)
                                    Vendor Self-Hosted Server  \
NaN                                    NaN                NaN
NaN                                 aspect               cost
NaN               storage: 1 TB for 1 year             $89.99
NaN             storage: 100 TB for 1 year             $32400
NaN  compute: 20 cores, 1TB of RAM, 5 GPUs             $10749
NaN                     data upload: 10 TB             $10584
NaN                   data download: 10 TB             $10584

                                            Unnamed: 2  \
NaN                                                NaN
NaN                                         source URL
NaN  https://www.ebay.com/itm/NAS-Acer-Aspire-Easy-...
NaN  https://www.emergentsx.com/listings/product/10...
NaN  http://www.deltaserverstore.com/dell-r910.html...
NaN                https://www.ibm.com/cloud/bandwidth
NaN                https://www.ibm.com/cloud/bandwidth

                                 Unnamed: 3
NaN                                     NaN
NaN                                    note
NaN                          Buying it off.
NaN                                     NaN
NaN  1 TB RAM,24Core + 6 GPU = ($6000+4749)
NaN                              882$/month
NaN          Would be covered in above cost
df.shape= (7, 4)
                                    Vendor <<NAME OF COMPANY>>  \
NaN                                    NaN                 NaN
NaN                                 aspect        cost ( in $)
NaN               storage: 1 TB for 1 year               238.8
NaN             storage: 100 TB for 1 year               23880
NaN  compute: 20 cores, 1TB of RAM, 5 GPUs                3226
NaN                     data upload: 10 TB                free
NaN                   data download: 10 TB               13320

                                            Unnamed: 2  \
NaN                                                NaN
NaN                                         source URL
NaN  https://www.enterprisestorageforum.com/cloud-s...
NaN  https://www.enterprisestorageforum.com/cloud-s...
NaN  https://ark.intel.com/content/www/us/en/ark/pr...
NaN  https://www.enterprisestorageforum.com/cloud-s...
NaN  https://www.enterprisestorageforum.com/cloud-s...

                                            Unnamed: 3
NaN                                                NaN
NaN                                               note
NaN  Calculated by rate given per mb  and 5gb free ...
NaN  Calculated by rate given per mb  and 5gb free ...
NaN  Cost I mentioned is refered to 20 cores ,1.5 T...
NaN                    free data transfer to the cloud
NaN  (0-1) TB rate is $0.12/gb and (1-10) TB rate i...
df.shape= (7, 4)
                                    Vendor Google Cloud  \
NaN                                    NaN          NaN
NaN                                 aspect         cost
NaN               storage: 1 TB for 1 year       319.44
NaN             storage: 100 TB for 1 year        32368
NaN  compute: 20 cores, 1TB of RAM, 5 GPUs        54699
NaN                     data upload: 10 TB       130980
NaN                   data download: 10 TB       130980

                                            Unnamed: 2     Unnamed: 3
NaN                                                NaN            NaN
NaN                                         source URL           note
NaN  https://cloud.google.com/products/calculator/#...            NaN
NaN  https://cloud.google.com/products/calculator/#...            NaN
NaN  https://cloud.google.com/products/calculator/#...            NaN
NaN  https://cloud.google.com/products/calculator/#...            NaN
NaN                                                NaN  Nodes Spanner
df.shape= (7, 4)
                                    Vendor       Google  \
NaN                                    NaN          NaN
NaN                                 aspect         cost
NaN               storage: 1 TB for 1 year       319.49
NaN             storage: 100 TB for 1 year   31,948.80
NaN  compute: 20 cores, 1TB of RAM, 5 GPUs  1.21659e+06
NaN                     data upload: 10 TB        12000
NaN                   data download: 10 TB        12000

                                            Unnamed: 2  \
NaN                                                NaN
NaN                                         source URL
NaN  https://cloud.google.com/products/calculator/#...
NaN  https://cloud.google.com/products/calculator/#...
NaN  https://cloud.google.com/products/calculator/#...
NaN  https://cloud.google.com/storage/pricing#archi...
NaN  https://cloud.google.com/storage/pricing#archi...

                                            Unnamed: 3
NaN                                                NaN
NaN                                               note
NaN                                                NaN
NaN                                                NaN
NaN                                           One Year
NaN  Year Month - Network Usage & Transfer tool fee...
NaN  Year Month - Network Usage & Transfer tool fee...
df.shape= (7, 4)
                                    Vendor <<MICROSOFT>>  \
NaN                                    NaN           NaN
NaN                                 aspect          cost
NaN               storage: 1 TB for 1 year         33.24
NaN             storage: 100 TB for 1 year       2092.44
NaN  compute: 20 cores, 1TB of RAM, 5 GPUs       23117.6
NaN                     data upload: 10 TB           160
NaN                   data download: 10 TB           160

                                            Unnamed: 2  \
NaN                                                NaN
NaN                                         source URL
NaN  https://azure.microsoft.com/en-us/pricing/calc...
NaN  https://azure.microsoft.com/en-us/pricing/calc...
NaN  https://azure.microsoft.com/en-us/pricing/calc...
NaN  https://docs.microsoft.com/en-us/azure/storage...
NaN  https://azure.microsoft.com/en-us/pricing/deta...

                                            Unnamed: 3
NaN                                                NaN
NaN                                               note
NaN  per month it takes 2.77$ for 84GB therefore by...
NaN  per month for 8333.3GB data costs $174.37 ther...
NaN              Effective per month it costs $1926.47
NaN  Azure Import/Export service is used to securel...
NaN  Azure Import/Export service enables you to tra...
df.shape= (7, 4)
                         Vendor  Amazon  \
NaN                         NaN     NaN
NaN                      aspect    cost
NaN    storage: 1 TB for 1 year     276
NaN  storage: 100 TB for 1 year     552
NaN                     compute  168420
NaN          data upload: 10 TB       0
NaN        data download: 10 TB     900

                                        Unnamed: 2  \
NaN                                            NaN
NaN                                     source URL
NaN             https://aws.amazon.com/s3/pricing/
NaN             https://aws.amazon.com/s3/pricing/
NaN  https://aws.amazon.com/ec2/pricing/on-demand/
NaN             https://aws.amazon.com/s3/pricing/
NaN             https://aws.amazon.com/s3/pricing/

                                            Unnamed: 3
NaN                                                NaN
NaN                                               note
NaN        Data Transfer IN To Amazon S3 From Internet
NaN          First 50 TB / Month (S3 standard storage)
NaN  On demand pricing (per hour) x1.32xlarge (19.2...
NaN        Data Transfer IN To Amazon S3 From Internet
NaN           Data Returned by S3 Select (S3 standard)
df.shape= (10, 4)
df.shape= (9, 4)
df.shape= (30, 4)
df.shape= (7, 4)
                                        Vendor  \
NaN                                        NaN
NaN                                     aspect
NaN                   storage: 1 TB for 1 year
NaN                 storage: 100 TB for 1 year
NaN  compute: 20 cores, 1TB of RAM, and 5 GPUs
NaN                         data upload: 10 TB
NaN                       data download: 10 TB

                 MICROSOFT; NVIDIA (for GPUs)  \
NaN                                       NaN
NaN                                      cost
NaN                                    2803.2
NaN                                  ~$23,360
NaN                                   92744.6
NaN   *Read Operations (per 10,000) = $0.0014
NaN  *Write Operations (per 10,000) = $0.0175

                                            Unnamed: 2  \
NaN                                                NaN
NaN                                         source URL
NaN  https://azure.microsoft.com/en-us/pricing/deta...
NaN  https://azure.microsoft.com/en-us/pricing/deta...
NaN  https://www.dell.com/en-us/work/shop/accessori...
NaN  https://azure.microsoft.com/en-us/pricing/deta...
NaN  https://azure.microsoft.com/en-us/pricing/deta...

                                            Unnamed: 3
NaN                                                NaN
NaN                                               note
NaN                   ~$233.60/month*12 =  $2803.20/yr
NaN              (~$467.20/month)*12*50 =  ~$23,360/yr
NaN  (~$467.20/month)*(2.5 (for 20 cores))*(12mns)=...
NaN  Pricing was given under the "Operations and da...
NaN  Pricing was given under the "Operations and da...
df.shape= (7, 4)
                         Vendor Microsoft   \
NaN                         NaN        NaN
NaN                      aspect       cost
NaN    storage: 1 TB for 1 year        420
NaN  storage: 100 TB for 1 year      34800
NaN                     compute    34689.6
NaN          data upload: 10 TB       free
NaN        data download: 10 TB        870

                                            Unnamed: 2  \
NaN                                                NaN
NaN                                         source URL
NaN  https://azure.microsoft.com/en-us/pricing/deta...
NaN  https://azure.microsoft.com/en-us/pricing/deta...
NaN  https://azure.microsoft.com/en-us/pricing/deta...
NaN  https://azure.microsoft.com/en-us/pricing/deta...
NaN  https://azure.microsoft.com/en-us/pricing/deta...

                                            Unnamed: 3
NaN                                                NaN
NaN                                               note
NaN                                   $35 a month x 12
NaN                                $2,900 a month x 12
NaN  Unable to find exact requirements. Price show ...
NaN                                                NaN
NaN                                                NaN
df.shape= (7, 4)
                                    Vendor Self-hosted  \
NaN                                    NaN         NaN
NaN                                 aspect        cost
NaN               storage: 1 TB for 1 year         NaN
NaN             storage: 100 TB for 1 year        2895
NaN  compute: 20 cores, 1TB of RAM, 5 GPUs     37653.2
NaN                     data upload: 10 TB         NaN
NaN                   data download: 10 TB         NaN

                                            Unnamed: 2  \
NaN                                                NaN
NaN                                         source URL
NaN                                                NaN
NaN  https://www.newegg.com/Product/Product.aspx?It...
NaN  http://www.broadberry.com/xeon-e5v3-rackmount-...
NaN                                                NaN
NaN                                                NaN

                                            Unnamed: 3
NaN                                                NaN
NaN                                               note
NaN                                                NaN
NaN                                       60TB storage
NaN  Server specs contain: 20cores, 1TB and 48TB (o...
NaN                                                NaN
NaN                                                NaN
df.shape= (7, 4)
                                    Vendor    Amazon  \
NaN                                    NaN       NaN
NaN                                 aspect      cost
NaN               storage: 1 TB for 1 year     59.99
NaN             storage: 100 TB for 1 year      2250
NaN  compute: 20 cores, 1TB of RAM, 5 GPUs  17160130
NaN                     data upload: 10 TB    free?
NaN                   data download: 10 TB      3000

                                            Unnamed: 2  \
NaN                                                NaN
NaN                                         source URL
NaN  https://www.amazon.com/b?ie=UTF8&node=16591160011
NaN                 https://aws.amazon.com/s3/pricing/
NaN                     https://awstcocalculator.com/#
NaN      https://aws.amazon.com/snowball-edge/pricing/
NaN      https://aws.amazon.com/snowball-edge/pricing/

                                            Unnamed: 3
NaN                                                NaN
NaN                                               note
NaN                                                NaN
NaN  $1150+$1100 first 50 gigs is 0.023 per gb. Nex...
NaN                           used the cost calculator
NaN  data tranfer in is free, if that is the same t...
NaN                                                NaN
df.shape= (7, 4)
                                    Vendor Amazon AWS  \
NaN                                    NaN        NaN
NaN                                 aspect       cost
NaN               storage: 1 TB for 1 year     281.28
NaN             storage: 100 TB for 1 year      27648
NaN  compute: 20 cores, 1TB of RAM, 5 GPUs      29075
NaN                     data upload: 10 TB          0
NaN                   data download: 10 TB    11058.1

                                            Unnamed: 2  \
NaN                                                NaN
NaN                                         source URL
NaN  https://calculator.s3.amazonaws.com/index.html...
NaN  https://calculator.s3.amazonaws.com/index.html...
NaN  https://calculator.s3.amazonaws.com/index.html...
NaN  https://calculator.s3.amazonaws.com/index.html...
NaN  https://calculator.s3.amazonaws.com/index.html...

                                            Unnamed: 3
NaN                                                NaN
NaN                                               note
NaN                                          Amazon S3
NaN                                          Amazon S3
NaN                                         Amazon EC2
NaN  Looks like its free with price of base EC2 ser...
NaN                                                NaN
df.shape= (7, 4)
                                    Vendor  \
NaN                                    NaN
NaN                                 aspect
NaN               storage: 1 TB for 1 year
NaN             storage: 100 TB for 1 year
NaN  compute: 20 cores, 1TB of RAM, 5 GPUs
NaN                     data upload: 10 TB
NaN                   data download: 10 TB

                                   Amazon Web Services  \
NaN                                                NaN
NaN                                               cost
NaN            First 50 TB / Month $0.023/GB\n~ $23.00
NaN  First 50 TB / Month $0.023/GB\nNext 450 TB / M...
NaN           \t$1.872/hr *24*365\n~$16,398.72/ year\n
NaN                      No Cost; Free for Data upload
NaN              10TB/month for  $0.09 per GB\n~$90.00

                                            Unnamed: 2  \
NaN                                                NaN
NaN                                         source URL
NaN                 https://aws.amazon.com/s3/pricing/
NaN                 https://aws.amazon.com/s3/pricing/
NaN  https://aws.amazon.com/marketplace/pp/B07GRMYQ...
NaN                 https://aws.amazon.com/s3/pricing/
NaN                 https://aws.amazon.com/s3/pricing/

                                            Unnamed: 3
NaN                                                NaN
NaN                                               note
NaN                                                NaN
NaN                                                NaN
NaN  Amazon Linux 2 AMI (HVM), SSD Volume Type \nh1...
NaN                                                NaN
NaN                                                NaN
df.shape= (7, 4)
                                    Vendor Google  \
NaN                                    NaN    NaN
NaN                                 aspect   cost
NaN               storage: 1 TB for 1 year     84
NaN             storage: 100 TB for 1 year   8400
NaN  compute: 20 cores, 1TB of RAM, 5 GPUs  26280
NaN                     data upload: 10 TB   Free
NaN                   data download: 10 TB    500

                                            Unnamed: 2  \
NaN                                                NaN
NaN                                         source URL
NaN  https://cloud.google.com/storage/pricing#price...
NaN  https://cloud.google.com/storage/pricing#price...
NaN  https://cloud.google.com/compute/pricing#custo...
NaN  https://cloud.google.com/storage/pricing#netwo...
NaN  https://cloud.google.com/storage/pricing#netwo...

                                            Unnamed: 3
NaN                                                NaN
NaN                                               note
NaN         Coldline storage only - access once a year
NaN         Coldline storage only - access once a year
NaN  Calculation of vcpu/memory/gpu per hour for on...
NaN                     Within the same location only
NaN                     Within the same location only
df.shape= (7, 4)
                                    Vendor   Amazon  \
NaN                                    NaN      NaN
NaN                                 aspect     cost
NaN               storage: 1 TB for 1 year   281.28
NaN             storage: 100 TB for 1 year  30411.2
NaN  compute: 20 cores, 1TB of RAM, 5 GPUs  66883.3
NaN                     data upload: 10 TB        0
NaN                   data download: 10 TB   147.24

                                         Unnamed: 2  \
NaN                                             NaN
NaN                                      source URL
NaN  https://calculator.s3.amazonaws.com/index.html
NaN  https://calculator.s3.amazonaws.com/index.html
NaN  https://calculator.s3.amazonaws.com/index.html
NaN  https://calculator.s3.amazonaws.com/index.html
NaN  https://calculator.s3.amazonaws.com/index.html

                                            Unnamed: 3
NaN                                                NaN